### ISSUE TITLE
[Optional] Small fixes and enhancements

### ISSUE THREAD

**Issue by cbouysset** [JustinYKC/FEPOPS#18]
These are just small enhancements/fixes that I noticed while going through the code or documentation, feel free to ignore them as I don't consider them blocking for the acceptance of the paper in JOSS:

- [x] Reorganize the benchmark files in a separate folder. Currently the notebooks and the `mol_filter.py` file are at the root of the repository, but to make it clear what they are for (especially the filtering file) they should be in a `benchmark` directory. Also the type hints for return types in `mol_file.py` should be `Optional[X]` instead of `X or None` in some places.
- [x] The `DudePreprocessor` class in the notebook is already defined in package, no need to redefine it in the notebook.
- [x] typo: `descriptor_sds` should be `descriptor_stds` [here](https://github.com/JustinYKC/FEPOPS/blob/master/src/fepops/fepops.py#L77)
- [x] Use the standard `warnings` or `logging` modules instead of `print` for warnings/errors/info. Also [here](https://github.com/JustinYKC/FEPOPS/blob/master/src/fepops/fepops.py#L555) the message will not be displayed, and it is a duplicate of [this print call](https://github.com/JustinYKC/FEPOPS/blob/master/src/fepops/fepops.py#L842-L844).
- [ ] The custom K-medoid implementation could be replaced by the one in the `sklearn-extra` package, which includes both PAM and CLARA algorithms described in the original FEPOPS implementation.
- [x] The output of CLI commands is not in a standard format (python list, numpy array…etc) which makes the `calc_sim` and `get_fepops` CLI commands hardly usable since they require manual editing to be parsed. They should be printed in a tab-separated format or JSON instead, or written to a file.
- [x] On the [welcome page of the docs](https://justinykc.github.io/FEPOPS/#:~:text=and%20is%20available%20here%3A%20readme), the link to the readme is broken (it works in the sidebar though)

**Comment by stevenshave** [comment]
Thanks for raising these points. We believe they have all been addressed and merged into the master branch in 2146bcf0b2737ea671cb4beed6cbfc5632f8baee, apart from the addition of the K-medoid implementation from sklearn-extra.  We would like to understand the techniques used more fully and measure impacts this will have on openfepops.  We envision integrating this into a future release as an optional method whilst under evaluation.

Reorganisation of the benchmarks folder and other miscellaneous files which were in the root of the fepops package has been undertaken with the creation of a fepops.utils package in efbd1a3284dff7f0547d7b4aeaa3d0b20d4914a6, placing benchmarking, filtering and preprocessing of the DUDE dataset into this utils group.  Care was taken to address typehint issues in b5893765565a7f1c38c0fe666472ae2de5a05aa0.

The notebook now imports the DudePreprocessor class from the utils submodule above, fixed in 7b929a16dc1eadfa1f4abfd4e80a4c2a7982cad9.

Typo addressed in acd95fba734d6b762783a87bb6d2316debb3005e.

The logging module is now used, rather than print statements to alert the user to potential issues, addressed in 79510738e246bfd1020079a3a77d5945547de7f2 and 79510738e246bfd1020079a3a77d5945547de7f2.

Output from the CLI subcommands get_fepops and calc_sim may now be captured in JSON format output files with the addition of a command line flag for these subcommands, addressed in 72a794eb3c58e371b76268f635b7297c46e32fb4.  The README.md and docs have been updated to reflect this change, all addressed in c7620c07867a803f9e1cacc7ba0c4b9e9ac1f7ed.

Broken link in documentation updated in fb7214bb07d07d4c049cc14141cfc14bc2ab4795.

Many thanks for your in-depth review and I hope we have addressed required issues.
Steve

**Comment by cbouysset** [comment]
I'll just add another optional one that I noticed while running the notebook, but `get_persistent_fepops_storage_object ` does not expose the underlying `kmeans_method` parameter which could be useful to speed things up from my understanding.

Again, feel free to ignore if not relevant (and close this issue yourself when done).

**Comment by stevenshave** [comment]
Great! I have added the kmeans_method argument to get_persistent_fepops_storage_object in 873f200d4bf680d65850c62175d41638f498f064. Many thanks.
