### ISSUE TITLE
Error when running "Explore_DUDE_diversity_set.ipynb"

### ISSUE THREAD

**Issue by hannahbaumann** [JustinYKC/FEPOPS#23]
Refers to the JOSS submission review: https://github.com/openjournals/joss-reviews/issues/5763:

I was able to run most of the example notebook, but for some reason my `res_df_dude_target_*.csv` files look different compared to the original files that were provided in the example, leading to an error when trying to generate the tables from the paper using this command:
```
display(pd.concat([pd.read_csv(f) for f in Path("data/dude/processed/diversity_set/").glob("res_df_dude_target_hivrt.csv")])
        .pivot(values='average_auroc_score',index='target', columns=['similarity_method'],)
        [['Morgan 2', 'RDKit', 'MACCS', 'OpenFEPOPS']])
```
      
The error is the following:

```
File ~/mambaforge/envs/fepops_311/lib/python3.10/site-packages/pandas/core/reshape/reshape.py:210, in _Unstacker._make_selectors(self)
    207 mask.put(selector, True)
    209 if mask.sum() < len(self.index):
--> 210     raise ValueError("Index contains duplicate entries, cannot reshape")
    212 self.group_index = comp_index
    213 self.mask = mask

ValueError: Index contains duplicate entries, cannot reshape
```

Even though the code that generates the .csv files for the different targets ran successfully without giving an error (calculating the different metrics for the 4 different methods), the output files are missing the Morgan 2 method, and instead have the row for the MACCS method duplicated which then leads to the error when trying to generate the table.

Output example: `res_df_dude_target_cp3a4.csv`

```
,target,similarity_method,smiles_count,actives_count,failed_smiles,failed_active_smiles,average_auroc_score,median_auroc_score,q1_auroc_score,q3_auroc_score
0,cp3a4,MACCS,11970,170,4,0,0.5815453804644352,0.5808045598707439,0.42871445517423656,0.45669245058145336
1,cp3a4,MACCS,11970,170,4,0,0.5815453804644352,0.5808045598707439,0.42871445517423656,0.45669245058145336
2,cp3a4,RDKit,11970,170,4,0,0.6133354937630608,0.6263335776833623,0.3858205965880757,0.3903332722458261
3,cp3a4,OpenFEPOPS,11970,170,4,0,0.6474616432055439,0.653921568627451,0.36536023801687506,0.391133003710131
```

I had run the example notebook as provided on the github page, but had skipped the first step of preparing the DUDE database and instead used the files provided in `data/dude/processed/diversity_set`
Do you have an idea what could be going on here? Please let me know if it would be helpful if I provided more details!

**Comment by stevenshave** [comment]
Hi @hannahbaumann, thank you for raising this issue.

I found an issue on my side with the jupyter notebook which contained a link pointing to version 2 of the data (which was incorrect as you note). Version 3 (released  2023-09-05) should be used.  Apologies for that, I have now updated the link in the notebook to point to v3 (https://doi.org/10.6084/m9.figshare.23951445.v3) in commit ef17f328ce58498828a11c8147b307d45308aa1e.

Another possible issue - can you confirm that you are using the latest version of the jupyter notebook (and/or redownload the new one with the corrected link to FigShare v3 files)? In your text above, you note that the cell which throws the error has glob string of `res_df_dude_target_hivrt.csv`, but in the current version it has the string `res_df_dude_target_*.csv`.  If you had changed it just for your testing purposes, then possibly the pivot is failing due to only one DataFrame being loaded.

The notebook works for me using V3 data and the most up-to-date notebook. I have :
1) Re-downloaded the V3 data zip file and rerun the notebook from the title `# Output summary AUROC results table as shown in the paper`. This reproduced the table in the paper.
2) Re-run the entire notebook including descriptor generation. This reproduced the table in the paper.

Please let me know if this fixes the issues.
Many thanks,
Steve

**Comment by hannahbaumann** [comment]
Hi @stevenshave : Thank you so much for your help!
I re-downloaded the data zip file (making sure to download v3) and I also re-downloaded the jupyter notebook from the master branch.
I was able to generate the tables from the paper when using the files form the data folder and only running the notebook from the title `# Output summary AUROC results table as shown in the paper`
However, when rerunning the entire notebook including descriptor generation I was still getting the same error. Something weird happens when generating the `auroc_scores_info_df`. In the first round of the loop 
```
info=pd.Series(dtype=object)
for sm_name, sm in similarity_methods.items():
        # Remove entries which did not return a mol
        info['target']=csv_file_path.stem.replace("dude_target_","")
```
the code correctly generates the dataframe for Morgan2, but then when calculating values for MACCS it replaces the Morgan2 column with MACCS and ends up having two duplicate MACCS columns, one rdkit and one openfepops column. I'll keep looking into this, but if you already have an idea of what could be going on on my side, please let me know!

**Comment by stevenshave** [comment]
Hi @hannahbaumann , sorry for the delay.  I'm travelling but will try to sort the MACCS/Morgan issues you are having soon.
Thanks,
Steve

**Comment by stevenshave** [comment]
Hi @hannahbaumann, I've rewritten the benchmark code somewhat and included some guards for results files existing in the current directory, along with changes to the loop which populates results files.  This works with me running it from scratch, and also with the intermediate files in the data zip (V3-as before).

Would you be able to re-download the notebook and check that the new version works for you.
Many thanks,
Steve

**Comment by hannahbaumann** [comment]
Thank you so much @stevenshave , I was now able to run it and got the same tables as in the pdf!
